// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPuIxQG07NP-ORDjjCsoVBacaACYkmLOM',
    appId: '1:569379494837:web:34cdfb9b5b1b26d2a5d7fc',
    messagingSenderId: '569379494837',
    projectId: 'app-tai-chinh',
    authDomain: 'app-tai-chinh.firebaseapp.com',
    storageBucket: 'app-tai-chinh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ItFZdP05vkOuVfl2H5W5vQlU_nY6yp4',
    appId: '1:569379494837:android:ab0e819081f42285a5d7fc',
    messagingSenderId: '569379494837',
    projectId: 'app-tai-chinh',
    storageBucket: 'app-tai-chinh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7YzlP0UJSaqtwj_o3dejmhAGVc1My5I',
    appId: '1:569379494837:ios:a8a15aac13d13cb4a5d7fc',
    messagingSenderId: '569379494837',
    projectId: 'app-tai-chinh',
    storageBucket: 'app-tai-chinh.appspot.com',
    iosClientId: '569379494837-j08fpfpnobfqr80hjo1ad39o9a7r2cit.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyappV1',
  );
}
